name: DataStreamRS Actions
run-name: ${{ github.actor }} started 🚀
on: [ push ]
jobs:
  Check:
    runs-on: ubuntu-22.04
    container: rust:1.77-slim
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt && rustup component add clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo build
      - run: cargo test
